version: '3.8'

services:
  frontend_g:
    image: node:lts
    container_name: frontend_g
    working_dir: /app
    volumes:
      - ../project/front:/app
    ports:
      - "5173:5173"
    entrypoint: ["/app/entrypoint.sh"]
    networks:
      - symfony

  backend_g:
    build:
      context: .
      dockerfile: dockerfiles/backend/Dockerfile
    container_name: backend_g
    working_dir: /var/www/html
    volumes:
      - ../project/backend:/var/www/html
    ports:
      - "9000:9000"
    command: >
      sh -c "composer install && php-fpm"
    environment:
      DATABASE_URL: "mysql://symfony:symfony_password@mysql_g:3306/symfony_db"
    depends_on:
      - mysql_g
    networks:
      - symfony

  nginx_g:
    image: nginx:alpine
    container_name: nginx_g
    volumes:
      - ../project/backend:/var/www/html
      - ../conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - backend_g
    networks:
      - symfony

  mysql_g:
    image: mysql:8.0
    container_name: mysql_g
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  db_data:
