nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null


# config/packages/nelmio_cors.yaml
#nelmio_cors:
#    defaults:
#        allow_origin: ['*']  # Permite todas las solicitudes de cualquier dominio
#        allow_credentials: false
#        allow_headers: ['Content-Type', 'Authorization']
#        expose_headers: ['Link']
#        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#        max_age: 3600
#    paths:
#        '^/api/':  # Aplica las reglas CORS solo a las rutas que comienzan con /api/
#            allow_origin: ['*']
#            allow_headers: ['Content-Type', 'Authorization']
#            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
